name: Publish Package

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: bun install

    - name: Lint code
      run: bun run lint

    - name: Format code
      run: bun run format

    - name: Build project
      run: bun run build

    - name: Publish to npm
      run: bun publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
